#!/bin/sh

CONFIG=~/.config/knightadjusterrc

THRESHOLD_DARK=4800

PLASMA_DARK=BreezeDark
PLASMA_LIGHT=BreezeClassic
CURSOR_DARK=Breeze_Snow
CURSOR_LIGHT=breeze_cursors
ICON_DARK=breeze-dark
ICON_LIGHT=breeze
KONSOLE_DARK=Dark
KONSOLE_LIGHT=Light
CHROME_DARK=1
CHROME_LIGHT=9

BIN_PLASMA=plasma-apply-colorscheme
BIN_CURSOR=plasma-apply-cursortheme
BIN_ICON=$(locate plasma-changeicons)

export DISPLAY=:0
export XDG_RUNTIME_DIR=/run/user/$(id -u)

if [ -e "$CONFIG" ]; then . "$CONFIG"; fi

if [ $(qdbus org.kde.KWin /ColorCorrect org.kde.kwin.ColorCorrect.currentTemperature) -lt $THRESHOLD_DARK ]; then
	plasmacolors=$PLASMA_DARK
	cursorcolors=$CURSOR_DARK
	iconcolors=$ICON_DARK
	konsolecolors=$KONSOLE_DARK
	chromecolors=$CHROME_DARK
else
	plasmacolors=$PLASMA_LIGHT
	cursorcolors=$CURSOR_LIGHT
	iconcolors=$ICON_LIGHT
	konsolecolors=$KONSOLE_LIGHT
	chromecolors=$CHROME_LIGHT
fi

plasmacurrent=$(grep ColorScheme= ~/.config/kdeglobals)

if [ "x$plasmacurrent" = "xColorScheme=$plasmacolors" ]; then
	echo no change $plasmacurrent
	return
fi

$BIN_PLASMA $plasmacolors
$BIN_CURSOR $cursorcolors
$BIN_ICON $iconcolors

dbuskonsole=$(qdbus | grep konsole)

if [ "x$dbuskonsole" = x ]; then
	sed -i s/DefaultProfile=.*/DefaultProfile=$konsolecolors.profile/ ~/.config/konsolerc
else
	for bus in $dbuskonsole; do
		for win in $(qdbus $bus | grep /Windows/); do
			qdbus $bus $win org.kde.konsole.Window.setDefaultProfile $konsolecolors
			break
		done
		for ses in $(qdbus $bus | grep /Sessions/); do
			qdbus $bus $ses org.kde.konsole.Session.setProfile $konsolecolors
		done
	done
fi

chromepid=$(pgrep chrome)

if [ "x$chromepid" = x ]; then
	sed -i s/enable-force-dark@./enable-force-dark@$chromecolors/ ~/.config/google-chrome*/'Local State'
else
	if kdialog --yesno 'Restart chrome?'; then
		pkill -INT -f chrome
		pidwait chrome
		sed -i s/enable-force-dark@./enable-force-dark@$chromecolors/ ~/.config/google-chrome*/'Local State'
		qdbus org.kde.klauncher5 /KLauncher org.kde.KLauncher.kdeinit_exec google-chrome --restore-last-session "" ""
	fi
fi
