#!/bin/sh

CONFIG=~/.config/knightadjusterrc

THRESHOLD_DARK=4800

PLASMA_DARK=BreezeDark
PLASMA_LIGHT=BreezeClassic
ICON_DARK=breeze-dark
ICON_LIGHT=breeze
KONSOLE_DARK=Dark
KONSOLE_LIGHT=Light

BIN_PLASMA=plasma-apply-colorscheme
BIN_ICON=$(locate plasma-changeicons)

export DISPLAY=:0
export XDG_RUNTIME_DIR=/run/user/$(id -u)

if [ -e "$CONFIG" ]; then . "$CONFIG"; fi

if [ $(qdbus org.kde.KWin /ColorCorrect org.kde.kwin.ColorCorrect.currentTemperature) -lt $THRESHOLD_DARK ]; then
	plasmacolors=$PLASMA_DARK
	iconcolors=$ICON_DARK
	konsolecolors=$KONSOLE_DARK
else
	plasmacolors=$PLASMA_LIGHT
	iconcolors=$ICON_LIGHT
	konsolecolors=$KONSOLE_LIGHT
fi

$BIN_PLASMA $plasmacolors
$BIN_ICON $iconcolors

dbuskonsole=$(qdbus | grep konsole)

if [ "x$dbuskonsole" = x ]; then
	sed -i s/DefaultProfile=.*/DefaultProfile=$konsolecolors.profile/ ~/.config/konsolerc
else
	for bus in $dbuskonsole; do
		for win in $(qdbus $bus | grep /Windows/); do
			qdbus $bus $win org.kde.konsole.Window.setDefaultProfile $konsolecolors
			break
		done
		for ses in $(qdbus $bus | grep /Sessions/); do
			qdbus $bus $ses org.kde.konsole.Session.setProfile $konsolecolors
		done
	done
fi
